apiVersion: batch/v1
kind: CronJob
metadata:
  name: todoapp-health
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl
              image: busyboxplus:curl
              imagePullPolicy: IfNotPresent
              command: ["/bin/sh", "-c"]
              args:
                - |
                  echo "$(date) checking health"
                  curl -fsS --max-time 5 http://todoapp-service.todoapp.svc.cluster.local/api/health
              resources:
                requests:
                  cpu: "10m"
                  memory: "16Mi"
                limits:
                  cpu: "50m"
                  memory: "32Mi"
          restartPolicy: Never